version: "3"
services:
  client:
    image: "jonhourcade/docker-client"
    mem_limit: 128m
    # hostname is used by nginx to route traffic
    # nginx will route traffic from / to http://client:3000
    # those hostnames match proxy_pass rules in the default.conf file
    hostname: client
  server:
    image: "jonhourcade/docker-server"
    mem_limit: 128m
    hostname: api
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
      - PGUSER=$PGUSER
      - PGHOST=$PGHOST
      - PGDATABASE=$PGDATABASE
      - PGPASSWORD=$PGPASSWORD
      - PGPORT=$PGPORT
  worker:
    image: "jonhourcade/docker-worker"
    mem_limit: 128m
    # we don't really need to set the hostname for worker
    # cause no other services need to reach out to it
    hostname: worker
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
  nginx:
    image: "jonhourcade/docker-nginx"
    mem_limit: 128m
    # we don't really need to set the hostname for nginx
    # cause no other services need to reach out to it
    hostname: nginx 
    ports:
      # map the host machine port 80 to the nginx container port 80
      # nginx by default listens on port 80
      - "80:80"